// Code generated by "stringer -type=Month"; DO NOT EDIT.

package julian

import "strconv"

const _Month_name = "JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember"

var _Month_index = [...]uint8{0, 7, 15, 20, 25, 28, 32, 36, 42, 51, 58, 66, 74}

func (i Month) String() string {
	i -= 1
	if i < 0 || i >= Month(len(_Month_index)-1) {
		return "Month(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
